version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    reviewers:
      - "@maintainers"
    assignees:
      - "@security-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for npm packages (frontend)
  - package-ecosystem: "npm"
    directory: "/client/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    reviewers:
      - "@frontend-team"
    assignees:
      - "@security-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "npm"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    # Group updates by type
    groups:
      eslint-plugins:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      svelte-ecosystem:
        patterns:
          - "svelte*"
          - "@sveltejs/*"
        update-types:
          - "minor"
          - "patch"
      dev-tools:
        patterns:
          - "prettier*"
          - "vite*"
          - "vitest*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      ui-dependencies:
        patterns:
          - "tailwind*"
          - "@tailwindcss/*"
          - "lucide-*"
          - "clsx"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    reviewers:
      - "@devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    reviewers:
      - "@devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 2