version: '3.8'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - drone-data:/data
    restart: always
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO:-http}
      - DRONE_USER_CREATE=username:admin,admin:true
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=${DRONE_RPC_PROTO:-http}
      - DRONE_RPC_HOST=${DRONE_RPC_HOST:-drone-server}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME:-my-runner}
      - DRONE_DEBUG=true
      - DRONE_TRACE=true

volumes:
  drone-data: 