version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gosec
  disable:
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports 