run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - gocritic
    - revive
    - gocyclo
    - dupl
    - goconst
    - gomnd
    - lll
    - nakedret
    - noctx
    - paralleltest
    - tagliatelle
    - tparallel
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gomnd:
    checks: argument,case,condition,operation,return,assign
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  tagliatelle:
    case:
      rules:
        json: camel
        yaml: camel
        xml: camel

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - goconst
    - path: internal/websocket/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0 