run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

linters-settings:
  goimports:
    local-prefixes: fethur

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec 