version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

formatters:
  enable:
    - gofmt 